name: Static analysis
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  lint_and_typing:
    container:
      image: fedora:latest
    runs-on: ubuntu-latest
    steps:
      - name: Check out sources
        uses: actions/checkout@v2

      - name: Install build environment
        run: dnf --assumeyes install dnf-plugins-core python3-pylint python3-mypy

      - name: Install build dependencies
        run: |
            dnf --assumeyes builddep --spec retrace-server.spec
            # For the pyfaf imports.
            dnf --assumeyes copr enable @abrt/faf-el8-devel
            dnf --assumeyes install faf python3-createrepo_c

      - name: Build
        run: |
          meson build
          ninja -C build

      - name: Run Mypy
        run: |
          cd build
          stubgen --output mypy_stubs --package createrepo_c --package dnf --package hawkey \
            --package pyfaf
          MYPYPATH=$(pwd)/mypy_stubs mypy --config-file=../mypy.ini src/
          MYPYPATH=$(pwd)/mypy_stubs:$(pwd)/src/ mypy \
            --config-file=../mypy.ini \
            --scripts-are-modules \
            src/coredump2packages \
            src/retrace-server-bugzilla-query \
            src/retrace-server-bugzilla-refresh \
            src/retrace-server-cleanup \
            src/retrace-server-interact \
            src/retrace-server-plugin-checker \
            src/retrace-server-reposync \
            src/retrace-server-reposync-faf \
            src/retrace-server-task \
            src/retrace-server-worker

      - name: Run Pylint
        if: always()
        run: |
          cd build
          python3 -m pylint --rcfile=pylintrc --output-format=colorized \
            src/plugins \
            src/retrace \
            src/coredump2packages \
            src/retrace-server-bugzilla-query \
            src/retrace-server-bugzilla-refresh \
            src/retrace-server-cleanup \
            src/retrace-server-interact \
            src/retrace-server-plugin-checker \
            src/retrace-server-reposync \
            src/retrace-server-reposync-faf \
            src/retrace-server-task \
            src/retrace-server-worker \
            test
